### ISSUE TITLE
Allow to use nesbot/carbon: ^2.67

### ISSUE THREAD

**Issue by ihorchepurnyi** [CrazyTapok-bit/tgWebValid#76]
Hello,

Thank you very much for your package!

I’m trying to use it in a Laravel project, but upgrading to the latest version is challenging because Laravel specifies the following version of Carbon in the composer.json file:

```
"nesbot/carbon": "^2.67"
```

Is there any chance you could allow this version in your package?

**Comment by CrazyTapok-bit** [comment]
Hello

Glad that our package is useful to you)

Regarding the upgrade, I'm not sure that downgrading would be the right decision to avoid causing conflicts and possible crashes for other users

However, I understand that you are most likely running Laravel 10, and one option I can suggest is to upgrade to version 11. That way you'll have `"nesbot/carbon": "^2.72.2|^3.0"` and that's it will work great

Alternatively, you can temporarily use `--ignore-platform-reqs`

If this doesn't work for you for some reason, then as a last resort I'm willing to look into this possibility and add support for `"nesbot/carbon": "^2.67|^3.2"` as an alternative, or accept PR from you)

Let me know the result

**Comment by ihorchepurnyi** [comment]
Thank you for suggestions. It will be difficult to upgrade Laravel version in our case because we already on production. Will try the second approach with a `--ignore-platform-reqs`. Hope it will help!

**Comment by ihorchepurnyi** [comment]
Still seeing the error with dependencies. Tried the following command

```
composer update tg/tgwebvalid --ignore-platform-reqs
```
